### ISSUE TITLE
Broken Login and Logout Behavior with RTM Update

### ISSUE THREAD

**Issue by Steven-Roberts** [IdentityServer/IdentityServer3.Integration.AspNetCore#10]
After updating all my nuget packages to .NET Core 1.0.0, I noticed some strange login and logout behavior.  For example, when open the Identity Server welcome page, then visit /permissions, I am first asked to login.  If I enter incorrect credentials, sometimes I can no longer login on later attempts even if the credentials are correct.  The usual behavior after a failed login attempt is to keep the previously entered username in the username field. After the update, the username field is often filled with a username provided many attempts ago and not the one provided in the previous attempt.  Sometimes after logging out, visiting /permissions, then logging in with incorrect credentials, I get logged in as the user that was just logged out.  It's like the logging out failed and somehow the session was resumed.  By reverting the all nuget packages to rc2, these issues cease to exist.  I have created the simplest possible project that shows this behavior [here](https://github.com/Steven-Roberts/IdentityServerTest).  Check the project.json file for the set of dependencies that work and do not work.

**Comment by leastprivilege** [comment]
I heard other reports of weird behavior with ASP.NET Core RTM.

We never supported nor recommended using asp.net core - and that's not a platform I am testing for.

On the other hand, it seems to work for other people just fine. So not sure what to do.

Maybe open a question on StackOverflow to reach more people.

**Comment by timscriv** [comment]
I am having the same issue and saw the problem referenced in IdentityServer3 repo. I implemented the same thing for this repo and it seems to fix the issue with the RTM upgrade.

**Comment by samsopheak** [comment]
Hi, just wondering when can we expect the new build? Thanks

**Comment by leastprivilege** [comment]
Holiday season. Sorry. 

1-2 weeks I hope.

**Comment by brockallen** [comment]
Here's my proposal for fixes based upon this and other PRs: https://github.com/IdentityServer/IdentityServer3/pull/3132

**Comment by brockallen** [comment]
Ok, I merged it. Thanks for everyone researching this and essentially solving the problem with your efforts and PRs. Thanks!
