### ISSUE TITLE
Upgrade library to support ASP.NET Core RC2

### ISSUE THREAD

**Issue by kg73** [IdentityServer/IdentityServer3.Integration.AspNetCore#5]
This project is targeting the now deprecated 'dnx451' moniker. I am submitting this issue to open a pull request to merge in changes to update the project to support ASP.NET Core 1.0 RC2.

**Comment by kg73** [comment]
Submitted pull-request #6 to resolve

**Comment by leastprivilege** [comment]
see my comment on the PR.
