### ISSUE TITLE
Error with package nuget in project .Net Core Rc2 

### ISSUE THREAD

**Issue by andreslon** [IdentityServer/IdentityServer3.Integration.AspNetCore#8]
I have a error while  try install the package nuget  IdentityServer3.Integration.AspNetCore in a ne w project of ASP.NEt Core Rc2.

 
`Errors in D:\Project\sample.API\src\sample.API\sample.API.xproj
    Package IdentityServer3.Integration.AspNetCore 1.0.0-rc2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package IdentityServer3.Integration.AspNetCore 1.0.0-rc2 supports: net451 (.NETFramework,Version=v4.5.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.`

**Comment by leastprivilege** [comment]
yep - the whole point is that you use the integration package in a .NET host - not a netcore host.

Otherwise use idsrv4
